apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-cm
  namespace: apps
data:
  SPRING_CLOUD_GCP_SQL_INSTANCE_CONNECTION_NAME: "907024360443:europe-west3:ha-postgres"
  SPRING_CLOUD_GCP_SQL_IP_TYPES: "PRIVATE"
