apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-sa
  namespace: apps
  annotations:
    iam.gke.io/gcp-service-account: "ha-gke-cloudsql@zetta-online-project.iam.gserviceaccount.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: apps
  labels:
    app.kubernetes.io/name: inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory
    spec:
      serviceAccountName: inventory-sa
      containers:
        - name: inventory
          image: europe-west3-docker.pkg.dev/zetta-online-project/ha-gke-docker/inventory-service
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: inventory-cm
            - secretRef:
                name: inventory-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/products
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
    
