apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-sa
  namespace: apps
  annotations:
    iam.gke.io/gcp-service-account: "ha-gke-cloudsql@zetta-online-project.iam.gserviceaccount.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: apps
  labels:
    app.kubernetes.io/name: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: order
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order
    spec:
      serviceAccountName: order-sa
      containers:
        - name: order
          image: europe-west3-docker.pkg.dev/zetta-online-project/ha-gke-docker/order-service:2692496963874976aa53c98c9d9dc3c9c438605c
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: order-cm
            - secretRef:
                name: order-secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/orders
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
