
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-cm
  namespace: apps
data:
  SPRING_CLOUD_GCP_SQL_INSTANCE_CONNECTION_NAME: "907024360443:europe-west3:ha-postgres"
  SPRING_CLOUD_GCP_SQL_IP_TYPES: "PRIVATE"
  INVENTORY_SERVICE_URL: "http://inventory.apps.svc.cluster.local:8080"
