apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: apps
  labels:
    app.kubernetes.io/name: order
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: "order"
  selector:
    app.kubernetes.io/name: order